### ISSUE TITLE
failed to run custom build command for wayland-protocols v0.23.0

### ISSUE THREAD

**Issue by fschutt** [Smithay/wayland-rs#256]
I'm in the process in upgrading from 0.21.7 to 0.23 and it seems that one of the build script has changed in a way that handles file paths wrong. I had no problems with this on 0.21.7, but the API (in wayland_scanner) changed a lot. I'm currently on Ubuntu 17.04.

```
   Compiling wayland-protocols v0.23.0 (/home/user/Development/azul-dependencies/wayland-protocols-0.23.0)
error: failed to run custom build command for `wayland-protocols v0.23.0 (/home/user/Development/azul-dependencies/wayland-protocols-0.23.0)`
process didn't exit successfully: `/home/user/Development/azul-dependencies/winit-0.18.0/target/debug/build/wayland-protocols-1f2a531aacd0074c/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to open protocol file `./protocols/stable/presentation-time/presentation-time.xml`.', /home/user/Development/azul-dependencies/wayland-scanner-0.23.0/src/lib.rs:106:29
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:346
   7: wayland_scanner::load_xml::{{closure}}
             at ./<::std::macros::panic macros>:8
   8: <core::result::Result<T, E>>::unwrap_or_else
             at libcore/result.rs:774
   9: wayland_scanner::load_xml
             at /home/user/Development/azul-dependencies/wayland-scanner-0.23.0/src/lib.rs:105
  10: wayland_scanner::generate_code
             at /home/user/Development/azul-dependencies/wayland-scanner-0.23.0/src/lib.rs:121
  11: build_script_build::generate_protocol
             at ./build.rs:44
  12: build_script_build::main
             at ./build.rs:68
  13: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  17: std::rt::lang_start
             at libstd/rt.rs:74
  18: main
  19: __libc_start_main
  20: _start
```

**Comment by fschutt** [comment]
Sorry, my mistake. For some reason the `wayland-protocols/wlr-protocos` folder got lost.
