### ISSUE TITLE
A handler for wl_keyboard panicked

### ISSUE THREAD

**Issue by lovesegfault** [Smithay/wayland-rs#372]
I have an application written using `winit 0.2.4` and `wgpu 0.7.0`. When I attempt to run it on NixOS I see the following:
```
thread 'main' panicked at 'internal error: entered unreachable code', /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/window/mod.rs:218:77
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[wayland-client error] A handler for wl_keyboard panicked.
zsh: abort (core dumped)  cargo run --release -- -s /tmp/sensord.sock
``` 

And this is the backtrace:
```
   0: std::panicking::begin_panic
             at /nix/store/zmicd8c2fqrvklb6nvak6p7s6ys7ia1m-rust-1.50.0-nightly-2020-11-18-825637983/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: winit::platform_impl::platform::wayland::window::Window::new::{{closure}}::{{closure}}
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/window/mod.rs:218:77
   2: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /nix/store/zmicd8c2fqrvklb6nvak6p7s6ys7ia1m-rust-1.50.0-nightly-2020-11-18-825637983/lib/rustlib/src/rust/library/core/src/ops/function.rs:269:13
   3: wayland_client::imp::proxy::proxy_dispatcher::{{closure}}::{{closure}}
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/proxy.rs:412:25
   4: scoped_tls::ScopedKey<T>::with
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:171:13
   5: wayland_client::imp::proxy::proxy_dispatcher::{{closure}}
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/proxy.rs:409:21
   6: std::panicking::try::do_call
             at /nix/store/zmicd8c2fqrvklb6nvak6p7s6ys7ia1m-rust-1.50.0-nightly-2020-11-18-825637983/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
   7: __rust_try
   8: std::panicking::try
             at /nix/store/zmicd8c2fqrvklb6nvak6p7s6ys7ia1m-rust-1.50.0-nightly-2020-11-18-825637983/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
   9: std::panic::catch_unwind
             at /nix/store/zmicd8c2fqrvklb6nvak6p7s6ys7ia1m-rust-1.50.0-nightly-2020-11-18-825637983/lib/rustlib/src/rust/library/std/src/panic.rs:396:14
  10: wayland_client::imp::proxy::proxy_dispatcher
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/proxy.rs:376:15
  11: wl_closure_dispatch
  12: dispatch_event.isra.0
  13: wl_display_dispatch_queue_pending
  14: wl_display_roundtrip_queue
  15: wayland_client::imp::event_queue::EventQueueInner::sync_roundtrip::{{closure}}
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:85:17
  16: wayland_client::imp::event_queue::with_dispatch_meta::{{closure}}
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:24:57
  17: scoped_tls::ScopedKey<T>::set
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  18: wayland_client::imp::event_queue::with_dispatch_meta
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:24:5
  19: wayland_client::imp::event_queue::EventQueueInner::sync_roundtrip
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/native_lib/event_queue.rs:83:9
  20: wayland_client::event_queue::EventQueue::sync_roundtrip
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.28.3/src/event_queue.rs:191:9
  21: winit::platform_impl::platform::wayland::window::Window::new::{{closure}}
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/window/mod.rs:218:21
  22: calloop::loop_logic::LoopHandle<Data>::with_source
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.6.5/src/loop_logic.rs:153:9
  23: winit::platform_impl::platform::wayland::window::Window::new
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/wayland/window/mod.rs:216:9
  24: winit::platform_impl::platform::Window::new
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:277:17
  25: winit::window::WindowBuilder::build
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/window.rs:333:9
  26: winit::window::Window::new
             at /home/bemeurer/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/window.rs:359:9
  27: sensord_view::main::{{closure}}
             at ./src/main.rs:59:19
  28: standard_config::cli::run_application_inner
             at /home/bemeurer/src/inf-sys/standard_config/src/cli.rs:272:5
  29: standard_config::cli::run_application
             at /home/bemeurer/src/inf-sys/standard_config/src/cli.rs:138:30
  30: sensord_view::main
             at ./src/main.rs:37:5
  31: core::ops::function::FnOnce::call_once
             at /nix/store/zmicd8c2fqrvklb6nvak6p7s6ys7ia1m-rust-1.50.0-nightly-2020-11-18-825637983/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

My knee-jerk guess is that this is happening because it's trying to `dlopen` something which I did not `patchelf` to point to the right place in Nix, but I couldn't figure out what that would be.

Why is this happening?

**Comment by vberger** [comment]
It looks like this is actually a winit problem, as this `unreachable!()` was triggered:

https://github.com/rust-windowing/winit/blob/10a94c0794a86687118e8723992ad9ad63ea717a/src/platform_impl/linux/wayland/window/mod.rs#L218

So I suggest you report it there, if possible with a minimal example reproducing it, so that they can figure out what is happening. I'm not clear whether this is actually related to `dlopen` or `patchelf`. But in any case, `patchelf` issue or not, there is a bug to be fixed.

To make it easier to debug, you may patch winit to replace the line of code I pointed to with this, which should produce a more helpful error message:

```rust
event_queue.sync_roundtrip(&mut *winit_state, |event, object, _| {
    panic!(
        "[winit] Encountered an orphan event: {}@{} : {}",
        event.interface,
        object.as_ref().id(),
        event.name
    );
})
```

**Comment by yilinwei** [comment]
Hey, I had a similar issue with the same stack-trace on Nix. Running `strace` with `cargo run` showed that it couldn't find `libxkbcommon` on the `LD_LIBRARY_PATH`. Adding `nixpkgs.libxkbcommon` to the `LD_LIBRARY_PATH` fixes it. `It's strange, because I'm not on X at all; I'm on Wayland. 

Is this the same issue that you're facing @lovesegfault?

**Comment by lovesegfault** [comment]
@yilinwei Bingo! That's exactly what I was missing!

Thank you!

**Comment by vberger** [comment]
> It's strange, because I'm not on X at all; I'm on sway.

libxkbcommon is used by Wayland as well, it's not X-exclusive.

**Comment by yilinwei** [comment]
Huh TIL. I see that it's loaded [here](https://github.com/Smithay/client-toolkit/blob/f5c33897f9dff02cfc4c0b124127e8cab435c78d/src/seat/keyboard/ffi.rs#L177); still the error message in `winit` is misleading and it's probably worth raising an issue there.
